package com.medtroniclabs.microcoaching.data.db.entity

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * Append-only coaching interaction event.
 *
 * Schema follows DataDesign v1.1 §4.1 exactly. One row per CHW–coaching system interaction.
 * Written offline-first to Room, then synced to the MicroCoaching backend by SyncWorker.
 *
 * SPICE accesses pending events via [CoachingDataRepository.getPendingCoachingEvents]
 * or receives them via [MicroCoachingDataCallback.onCoachingEventsReady].
 *
 * Event taxonomy (eventType values):
 *   card_shown, card_skipped, card_accepted, counselling_used, audio_played
 *   quiz_started, module_quiz_attempted
 *   spice_action_observed, risk_flag_observed, equipment_anomaly_observed
 *   session_start, session_end
 *   digital_help_used
 */
@Entity(
    tableName = "coaching_event",
    indices = [
        Index(value = ["sync_status"]),
        Index(value = ["chw_id", "module_family_id"]),
        Index(value = ["session_id"]),
    ]
)
data class CoachingEventEntity(

    /** UUID — deduplication key for idempotent sync. Generated by SDK. */
    @PrimaryKey
    @ColumnInfo(name = "event_id")
    val eventId: String,

    /** Schema version for this entity. Increment on any structural change. */
    @ColumnInfo(name = "event_schema_version")
    val eventSchemaVersion: Int = 1,

    /** SDK build version at the time the event was recorded. */
    @ColumnInfo(name = "sdk_version")
    val sdkVersion: String,

    /**
     * Backend-required event grouping.
     * Values: coaching | learning | clinical_observed | digital | system
     */
    @ColumnInfo(name = "event_family")
    val eventFamily: String,

    // ── Session and visit context ─────────────────────────────────────────────

    /** UUID generated by SDK per app/coaching session. Groups events for troubleshooting. */
    @ColumnInfo(name = "session_id")
    val sessionId: String,

    /**
     * Our normalised visit key — mapped from SPICE encounterId at the SDK boundary.
     * Null for morning open / non-visit events such as session_start.
     */
    @ColumnInfo(name = "patient_visit_id")
    val patientVisitId: String? = null,

    /**
     * Longitudinal patient journey key from SPICE.
     * Nullable — availability not confirmed for all SPICE endpoints [TEAM-CONFIRM].
     */
    @ColumnInfo(name = "patient_track_id")
    val patientTrackId: String? = null,

    /**
     * SHA-256 hash of the raw SPICE patient_id.
     * The only patient identifier that is allowed to leave the device or enter analytics.
     * Null for non-patient events (session_start, digital_help_used, etc.).
     */
    @ColumnInfo(name = "patient_id_hash")
    val patientIdHash: String? = null,

    // ── Actor and tenant ──────────────────────────────────────────────────────

    /**
     * CHW identifier from the SPICE auth/session context.
     * Exact field path depends on SPICE auth model [WORKFLOW-INFERRED].
     */
    @ColumnInfo(name = "chw_id")
    val chwId: String,

    /**
     * Organisation identifier for multi-tenant isolation.
     * Nullable until confirmed from SPICE auth context [WORKFLOW-INFERRED].
     */
    @ColumnInfo(name = "tenant_id")
    val tenantId: Int? = null,

    /** Lowest geographic key. From SPICE get-patient-details [DOC-CONFIRMED]. */
    @ColumnInfo(name = "village_id")
    val villageId: String? = null,

    /**
     * Higher geographic aggregation key.
     * Derived from village_id via local mapping table — not a direct SPICE field [OUR-DESIGN].
     */
    @ColumnInfo(name = "upazila_id")
    val upazilaId: String? = null,

    // ── What happened ─────────────────────────────────────────────────────────

    /** Event type discriminator. See KDoc above for the full taxonomy. */
    @ColumnInfo(name = "event_type")
    val eventType: String,

    /**
     * Clinical or operational domain.
     * Values: hypertension | diabetes | maternal_anc | equipment | spice_digital
     */
    @ColumnInfo(name = "clinical_domain")
    val clinicalDomain: String? = null,

    /** Card type shown. Values: QUIZ | WALKTHROUGH | AUDIO_HELP | COUNSELLING_SUMMARY */
    @ColumnInfo(name = "card_type")
    val cardType: String? = null,

    /** What triggered the card. Values: hard | soft | morning */
    @ColumnInfo(name = "trigger_type")
    val triggerType: String? = null,

    /** Inference mode used to generate the card. Values: online | edge | cached */
    @ColumnInfo(name = "inference_mode")
    val inferenceMode: String? = null,

    // ── Quiz-specific (null for non-quiz events) ──────────────────────────────

    @ColumnInfo(name = "quiz_question_id")
    val quizQuestionId: String? = null,

    /** Index of the option the CHW selected (0-based). */
    @ColumnInfo(name = "selected_option")
    val selectedOption: Int? = null,

    @ColumnInfo(name = "is_correct")
    val isCorrect: Boolean? = null,

    // ── Module / card / quiz pipeline identifiers (v3.3+) ────────────────────

    /** Stable cross-version module family UUID. Matches ModuleFamily.id on the backend. */
    @ColumnInfo(name = "module_family_id")
    val moduleFamilyId: String? = null,

    /** Version-specific module row UUID. Matches Module.id on the backend. */
    @ColumnInfo(name = "module_id")
    val moduleId: String? = null,

    /** Stable card UUID from card_family_id field inside cards_json. */
    @ColumnInfo(name = "card_family_id")
    val cardFamilyId: String? = null,

    /** Stable question UUID (question_family_id). Maps to quiz_family_id in the wire contract. */
    @ColumnInfo(name = "quiz_family_id")
    val quizFamilyId: String? = null,

    /** Module version at the time of the event. Matches Module.version on the backend. */
    @ColumnInfo(name = "module_version")
    val moduleVersion: Int? = null,

    /**
     * Cumulative quiz score as a fraction (0.0–1.0) at the time this question was answered.
     * Backend contract enforces ge=0.0, le=1.0 — do NOT send values in 0–100 range.
     */
    @ColumnInfo(name = "quiz_score_pct")
    val quizScorePct: Float? = null,

    // ── Outcome ───────────────────────────────────────────────────────────────

    /**
     * Event-type-dependent outcome.
     * Values: accepted | skipped | used | dismissed
     */
    @ColumnInfo(name = "outcome")
    val outcome: String? = null,

    // ── AI output quality (null for non-AI events) ────────────────────────────

    /** Output validator result. Values: pass | fail | fallback */
    @ColumnInfo(name = "validator_status")
    val validatorStatus: String? = null,

    /** True if a pre-authored Bangla card was served instead of AI output. */
    @ColumnInfo(name = "fallback_used")
    val fallbackUsed: Boolean? = null,

    // ── Extensibility ─────────────────────────────────────────────────────────

    /** Additional data not covered by typed columns. Schema is event-type specific. */
    @ColumnInfo(name = "payload_json")
    val payloadJson: String? = null,

    /**
     * Behavioural gap UUID forwarded from the morning-cards response.
     * Only populated on `module_quiz_attempted` events where the module was
     * surfaced via the gap-driven morning surface. Serialised into
     * [TelemetryEventPayload.payloadJson] by [SyncPayloadMapper].
     */
    @ColumnInfo(name = "behavioural_gap_id")
    val behaviouralGapId: String? = null,

    // ── Network state ─────────────────────────────────────────────────────────

    /** Device connectivity at event time. Values: online | offline | restored */
    @ColumnInfo(name = "network_state")
    val networkState: String? = null,

    // ── Timestamps ────────────────────────────────────────────────────────────

    /** Event time as device-local epoch millis (always present). */
    @ColumnInfo(name = "timestamp_local")
    val timestampLocal: Long = System.currentTimeMillis(),

    /**
     * Event time as UTC epoch millis (NTP-corrected).
     * Null when NTP is unavailable (offline CHW devices).
     */
    @ColumnInfo(name = "timestamp_utc")
    val timestampUtc: Long? = null,

    // ── Sync ──────────────────────────────────────────────────────────────────

    /**
     * Sync lifecycle state.
     * Values: pending | synced | failed
     */
    @ColumnInfo(name = "sync_status")
    val syncStatus: String = "pending",

    /** Epoch millis when the event was successfully synced. Null until then. */
    @ColumnInfo(name = "synced_at")
    val syncedAt: Long? = null,

    /** Number of sync retry attempts. */
    @ColumnInfo(name = "retry_count")
    val retryCount: Int = 0,
)
